services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - sms
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: sms-backend
    restart: always
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DBNAME=student_management
      - NODE_ENV=production
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - sms
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:5000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

volumes:
  mongodb_data:

networks:
  sms:
    driver: bridge
