services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - sms
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: sms-backend
    restart: always
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DBNAME=student_management
      - NODE_ENV=production
      - ALLOWED_ORIGINS=http://localhost,http://localhost:80,http://localhost:5173
      - LOG_LEVEL=info
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - sms

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: sms-frontend
    restart: always
    environment:
      - VITE_API_URL=http://localhost:5000/api
    ports:
      - '80:80'
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - sms

volumes:
  mongodb_data:
    name: sms_mongodb_data

networks:
  sms:
    driver: bridge
